#!/bin/bash
#
# roguepc-gnome-terminal - Gnome Terminal customization for roguepc
#
#    Copyright (C) 2015 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. See <http://www.gnu.org/licenses/gpl.html>
#
# Launches the game in a new Gnome Terminal window using the custom profile


# default options
fullscreen=0
terms=({gnome,xterm}-256color xterm)
title='Rogue PC'
profile='rogue'

rogueargs=()
gamecmd=$(dirname "$(readlink -f "$0")")/src/rogue

usage() {
	echo "Launch Rogue PC in a new Gnome Terminal window using the custom profile"
	echo "Usage: ${0##.*/} [-h] [-f|--fullscreen] [rogue args]"
	exit
}

has_terminfo() {
	local term=$1
	local termfile=terminfo/${term:0:1}/$term
	[[ -r /lib/"$termfile"       ||  # ncurses-base package
	   -r /usr/share/"$termfile" ||  # ncurses-term package
	   -r /etc/"$termfile"       ||  # empty by default
	   -r "$HOME"/."$termfile"   ]]  # dir may not exist
}

# Pre-parse for `help`
for arg in "$@"; do [[ "$arg" == "-h" || "$arg" == "--help" ]] && usage ; done

while (( $# )); do
	case "$1" in
	-f|--full-screen) fullscreen=1;;
	*) rogueargs+=("$1");;
	esac
	shift
done

for term in "${terms[@]}"; do
	if has_terminfo "$term"; then
		break
	fi
done

gtargs=(--profile "$profile" --title "$title")

if ((fullscreen)); then
	gtargs+=(--full-screen)
fi

gnome-terminal "${gtargs[@]}" --execute env TERM="$term" "$gamecmd" "${rogueargs[@]}"
